### PR TITLE
V1.1 fixed recovery connection

### PR DESCRIPTION
**Pull request by Namsulee**
In case of disconnection, agent should be re-connected.
But websocket and message channel have been created in mainLoop.
Once changed to use global websocket and message in order to use each goroutine. 
But it has to be re-designed as effective code
Also modify Dockerfile to set up ENV in container and changed default server url to ec2.
(dockzen-launcher library updated as well)

### CODE REVIEW

**Comment by jiehwan** [comment]
i wrote privious review comment.
the main thread lifecycle is mismatched with callee thread (wsReceive).
it means that wsReceive's life is continued automatically in spite that main thread is restarted in case of error.
i think above new commit is fixed for this issue.

**Comment by sy1124kim** [comment]
check please!!! 

<local pc>
sy1124kim@sy1124kim:~/work/1.tizen/3.docker/3.dockerMgr/CSA/dockzen-agent$ docker run --name agent2 -v /var/run:/var/run:rw dockzen-agent:v1.0<br>
2017/07/27 04:46:15 Container-Service Agent starting<br>
2017/07/27 04:46:15 WI init function !!!<br>
2017/07/27 04:46:15 [WEBINTERFACE] Web connection start !!!<br>
2017/07/27 04:46:15 [SERVICES] Server URL = 13.124.64.10:80/ws<br>
2017/07/27 04:46:15 [WEBINTERFACE] http_proxy {}    <b><------ stop agent container !!!</b> <br>

**Comment by Namsulee** [comment]
You need to setup proxy, I will make procedure to test with EC2. Also, install ca-certificates with Seou l R &D.crt. Therefore you' d better to review in code level

**Comment by Namsulee** [comment]
@jiehwan like you said, the code is for v1.1  I have updated version in build.sh as v1.1 and then will update container to EC2 server. If I am wrong, let me know !

**Comment by wansuyoo** [comment]
@Namsu.
I'm requesting to make a meeting for sharing about server change. (Local to EC2)
For using ethernet in our develop env. proxy setting should be performed for using EC2.
I think I need more explanation about this commit.. :)

**Pull request merged**
