### PR TITLE
V1.1 apply coding rule

### PR DESCRIPTION
**Pull request by sy1124kim**
Apply Coding standard rule for whole agent code.
Below items are applied in this PR

    1. Add function description (go comment format)
    2. Add Typedef structure and enum description(go comment format)
    3. Change the first letter to lower case for static functions.

### CODE REVIEW

**Comment by jiehwan** [comment]
http://10.113.62.204:6060/pkg/agent/types/dockzenl/

**Comment by jiehwan** [comment]
Regarding godoc http site,
i have installed the dockzen-agent source into our server ~/dockzen/dockzen-agent with (-b v1.1-apply_coding_rule).
and execut the godoc command like below,
`dockzen-agent$ godoc -http=:6060 -goroot=$(pwd)`
anybody can modify this sources to test the documentation.

**Comment by jiehwan** [comment]
add commit removing not-used dockzenl package.

**Comment by sy1124kim** [comment]
Add package description and function description in agent folder.

**Comment by jiehwan** [comment]
please check again for the request in previous comment.

**Comment by jiehwan** [comment]
1. sync the name between folder and package name (for the main package)
2. define executable output binary name as "agent"

**Comment by jiehwan** [comment]
update if needed..
http://suprem.sec.samsung.net/confluence/display/TPLDOCKERC/golang+documentation

**Pull request merged**
